-- Creator:       MySQL Workbench 8.0.13/ExportSQLite Plugin 0.1.0
-- Author:        cyoun
-- Caption:       New Model
-- Project:       Name of the project
-- Changed:       2019-06-27 18:36
-- Created:       2019-06-25 14:09
PRAGMA foreign_keys = OFF;

-- Schema: MODER
ATTACH "MODER.sdb" AS "MODER";
BEGIN;
CREATE TABLE "MODER"."IMAGE_OBJECT"(
  "OBJECT_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL CHECK("OBJECT_ID">=0),
  "ORIGIN" VARCHAR(2000) NOT NULL,
  "WIDTH" INTEGER NOT NULL CHECK("WIDTH">=0),
  "HEIGHT" INTEGER NOT NULL CHECK("HEIGHT">=0),
  CONSTRAINT "OBJECT_ID_UNIQUE"
    UNIQUE("OBJECT_ID")
);
CREATE TABLE "MODER"."GUILD_ROLES"(
  "ROLE_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL CHECK("ROLE_ID">=0),
  "DISCORD_ROLE_ID" INTEGER NOT NULL CHECK("DISCORD_ROLE_ID">=0),
  "NAME" VARCHAR(100) NOT NULL,
  "COLOR" INTEGER NOT NULL CHECK("COLOR">=0),
  "PERMISSIONS" INTEGER NOT NULL CHECK("PERMISSIONS">=0),
  "POSITION" INTEGER NOT NULL CHECK("POSITION">=0),
  "MENTIONABLE" INTEGER NOT NULL CHECK("MENTIONABLE">=0),
  "HOISTED" INTEGER NOT NULL CHECK("HOISTED">=0),
  "LASTUPDATE" DATETIME NOT NULL,
  CONSTRAINT "ROLE_ID_UNIQUE"
    UNIQUE("ROLE_ID")
);
CREATE TABLE "MODER"."VIDEO_OBJECT"(
  "OBJECT_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL CHECK("OBJECT_ID">=0),
  "ORIGIN" VARCHAR(2000) NOT NULL,
  "WIDTH" INTEGER NOT NULL CHECK("WIDTH">=0),
  "HEIGHT" INTEGER NOT NULL CHECK("HEIGHT">=0),
  "DURATION" INTEGER NOT NULL CHECK("DURATION">=0),
  CONSTRAINT "OBJECT_ID_UNIQUE"
    UNIQUE("OBJECT_ID")
);
CREATE TABLE "MODER"."EMBED_AUTHOR_OBJECT"(
  "EMBED_OBJECT_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL CHECK("EMBED_OBJECT_ID">=0),
  "NAME" VARCHAR(256),
  "URL" VARCHAR(2000),
  "ICON" INTEGER CHECK("ICON">=0),
  CONSTRAINT "EMBED_OBJECT_ID_UNIQUE"
    UNIQUE("EMBED_OBJECT_ID"),
  CONSTRAINT "fk_EMBED_AUTHOR_OBJECT_IMAGE_OBJECT1"
    FOREIGN KEY("ICON")
    REFERENCES "IMAGE_OBJECT"("OBJECT_ID")
);
CREATE INDEX "MODER"."EMBED_AUTHOR_OBJECT.fk_EMBED_AUTHOR_OBJECT_IMAGE_OBJECT1_idx" ON "EMBED_AUTHOR_OBJECT" ("ICON");
CREATE TABLE "MODER"."EVENT_LOG"(
  "EVENT_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL CHECK("EVENT_ID">=0),
  "EVENT_TYPE" INTEGER NOT NULL CHECK("EVENT_TYPE">=0),
  "USER_ID" INTEGER CHECK("USER_ID">=0),
  "GUILD_ID" INTEGER CHECK("GUILD_ID">=0),
  "TIME" DATETIME NOT NULL,
  CONSTRAINT "EVENT_ID_UNIQUE"
    UNIQUE("EVENT_ID")
);
CREATE TABLE "MODER"."GENERIC_GUILD_MODERATION_LOG"(
  "EVENT_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL CHECK("EVENT_ID">=0),
  "EVENT_TYPE" INTEGER NOT NULL CHECK("EVENT_TYPE">=0),
  "USER_ID" INTEGER NOT NULL CHECK("USER_ID">=0),
  "REASON" VARCHAR(512),
  CONSTRAINT "EVENT_ID_UNIQUE"
    UNIQUE("EVENT_ID"),
  CONSTRAINT "fk_GENERIC_GUILD_MODERATION_LOG_EVENT_LOG1"
    FOREIGN KEY("EVENT_ID")
    REFERENCES "EVENT_LOG"("EVENT_ID")
);
CREATE TABLE "MODER"."EMBED_FOOTER_OBJECT"(
  "EMBED_OBJECT_ID" INTEGER PRIMARY KEY NOT NULL CHECK("EMBED_OBJECT_ID">=0),
  "TEXT" VARCHAR(2048) NOT NULL,
  "ICON" INTEGER NOT NULL CHECK("ICON">=0),
  CONSTRAINT "EMBED_OBJECT_ID_UNIQUE"
    UNIQUE("EMBED_OBJECT_ID"),
  CONSTRAINT "ICON_UNIQUE"
    UNIQUE("ICON"),
  CONSTRAINT "fk_EMBED_FOOTER_OBJECT_IMAGE_OBJECT1"
    FOREIGN KEY("ICON")
    REFERENCES "IMAGE_OBJECT"("OBJECT_ID")
);
CREATE TABLE "MODER"."MESSAGE_OBJECT"(
  "MESSAGE_OBJECT_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL CHECK("MESSAGE_OBJECT_ID">=0),
  "AUTHOR" INTEGER NOT NULL CHECK("AUTHOR">=0),
  "CONTENT" TEXT NOT NULL,
  "LAST_EDITED" DATETIME NOT NULL,
  "CHANNEL" INTEGER NOT NULL CHECK("CHANNEL">=0),
  "TTS?" INTEGER NOT NULL CHECK("TTS?">=0),
  "PINNED?" INTEGER NOT NULL CHECK("PINNED?">=0),
  "EVERYONE?" INTEGER NOT NULL CHECK("EVERYONE?">=0),
  "TYPE" INTEGER NOT NULL CHECK("TYPE">=0),
  CONSTRAINT "MESSAGE_OBJECT_ID_UNIQUE"
    UNIQUE("MESSAGE_OBJECT_ID")
);
CREATE TABLE "MODER"."PRESENCE_OBJECT"(
  "PRESENCE_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL CHECK("PRESENCE_ID">=0),
  "NAME" VARCHAR(50) NOT NULL,
  "TYPE" INTEGER CHECK("TYPE">=0),
  "RICHPRESENCE?" INTEGER NOT NULL CHECK("RICHPRESENCE?">=0),
  "URL" VARCHAR(2000),
  "TIMESINCE" DATETIME,
  "DETAILS" VARCHAR(100),
  "STATE" VARCHAR(100),
  "FLAG" INTEGER,
  "ASSET_BIG_IMAGE" INTEGER CHECK("ASSET_BIG_IMAGE">=0),
  "ASSET_BIG_TOOLTIP" VARCHAR(100),
  "ASSET_SMA_IMAGE" INTEGER CHECK("ASSET_SMA_IMAGE">=0),
  "ASSET_SMA_TOOLTIP" VARCHAR(100),
  "PARTY_CUR" INTEGER CHECK("PARTY_CUR">=0),
  "PARTY_MAX" INTEGER CHECK("PARTY_MAX">=0),
  CONSTRAINT "PRESENCE_ID_UNIQUE"
    UNIQUE("PRESENCE_ID"),
  CONSTRAINT "fk_PRESENCE_OBJECT_IMAGE_OBJECT1"
    FOREIGN KEY("ASSET_BIG_IMAGE")
    REFERENCES "IMAGE_OBJECT"("OBJECT_ID"),
  CONSTRAINT "fk_PRESENCE_OBJECT_IMAGE_OBJECT2"
    FOREIGN KEY("ASSET_SMA_IMAGE")
    REFERENCES "IMAGE_OBJECT"("OBJECT_ID")
);
CREATE INDEX "MODER"."PRESENCE_OBJECT.fk_PRESENCE_OBJECT_IMAGE_OBJECT1_idx" ON "PRESENCE_OBJECT" ("ASSET_BIG_IMAGE");
CREATE INDEX "MODER"."PRESENCE_OBJECT.fk_PRESENCE_OBJECT_IMAGE_OBJECT2_idx" ON "PRESENCE_OBJECT" ("ASSET_SMA_IMAGE");
CREATE TABLE "MODER"."MEMBER_OBJECT"(
  "MEMBER_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL CHECK("MEMBER_ID">=0),
  "USER_ID" INTEGER NOT NULL CHECK("USER_ID">=0),
  "USER_NAME" VARCHAR(32) NOT NULL,
  "USER_DISCRIMINATOR" INTEGER NOT NULL CHECK("USER_DISCRIMINATOR">=0),
  "MEMBER_NAME" VARCHAR(45),
  "DEFAULT_AVATAR" INTEGER NOT NULL CHECK("DEFAULT_AVATAR">=0),
  "AVATAR" INTEGER NOT NULL CHECK("AVATAR">=0),
  CONSTRAINT "MEMBER_ID_UNIQUE"
    UNIQUE("MEMBER_ID"),
  CONSTRAINT "fk_MEMBER_OBJECT_IMAGE_OBJECT1"
    FOREIGN KEY("AVATAR")
    REFERENCES "IMAGE_OBJECT"("OBJECT_ID")
);
CREATE TABLE "MODER"."GENERIC_GUILD_ROLE_LOG"(
  "EVENT_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL CHECK("EVENT_ID">=0),
  "EVENT_TYPE" INTEGER NOT NULL CHECK("EVENT_TYPE">=0),
  "ROLE" INTEGER NOT NULL CHECK("ROLE">=0),
  CONSTRAINT "EVENT_ID_UNIQUE"
    UNIQUE("EVENT_ID"),
  CONSTRAINT "ROLE_UNIQUE"
    UNIQUE("ROLE"),
  CONSTRAINT "fk_GENERIC_GUILD_ROLE_LOG_ROLES_copy11"
    FOREIGN KEY("ROLE")
    REFERENCES "GUILD_ROLES"("ROLE_ID"),
  CONSTRAINT "fk_GENERIC_GUILD_ROLE_LOG_EVENT_LOG1"
    FOREIGN KEY("EVENT_ID")
    REFERENCES "EVENT_LOG"("EVENT_ID")
);
CREATE TABLE "MODER"."MENTIONED_MESSAGE_OBJECT"(
  "MESSAGE_OBJECT_ID" INTEGER NOT NULL CHECK("MESSAGE_OBJECT_ID">=0),
  "USER_ID" INTEGER NOT NULL CHECK("USER_ID">=0),
  CONSTRAINT "fk_MENTIONED_MESSAGE_OBJECT_MESSAGE_OBJECT1"
    FOREIGN KEY("MESSAGE_OBJECT_ID")
    REFERENCES "MESSAGE_OBJECT"("MESSAGE_OBJECT_ID")
);
CREATE INDEX "MODER"."MENTIONED_MESSAGE_OBJECT.fk_MENTIONED_MESSAGE_OBJECT_MESSAGE_OBJECT1_idx" ON "MENTIONED_MESSAGE_OBJECT" ("MESSAGE_OBJECT_ID");
CREATE TABLE "MODER"."GENERIC_GUILD_USER_LOG"(
  "EVENT_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL CHECK("EVENT_ID">=0),
  "EVENT_TYPE" INTEGER NOT NULL CHECK("EVENT_TYPE">=0),
  "USER_ID" INTEGER NOT NULL CHECK("USER_ID">=0),
  "MEMBER" INTEGER CHECK("MEMBER">=0),
  "ONLINE_STATUS" INTEGER NOT NULL CHECK("ONLINE_STATUS">=0),
  "PRESENCE" INTEGER CHECK("PRESENCE">=0),
  CONSTRAINT "USERID_UNIQUE"
    UNIQUE("EVENT_ID"),
  CONSTRAINT "fk_GENERIC_GUILD_USER_LOG_EVENT_LOG1"
    FOREIGN KEY("EVENT_ID")
    REFERENCES "EVENT_LOG"("EVENT_ID"),
  CONSTRAINT "fk_GENERIC_GUILD_USER_LOG_MEMBER_OBJECT1"
    FOREIGN KEY("MEMBER")
    REFERENCES "MEMBER_OBJECT"("MEMBER_ID"),
  CONSTRAINT "fk_GENERIC_GUILD_USER_LOG_PRESENCE_OBJECT1"
    FOREIGN KEY("PRESENCE")
    REFERENCES "PRESENCE_OBJECT"("PRESENCE_ID")
);
CREATE INDEX "MODER"."GENERIC_GUILD_USER_LOG.fk_GENERIC_GUILD_USER_LOG_PRESENCE_OBJECT1_idx" ON "GENERIC_GUILD_USER_LOG" ("PRESENCE");
CREATE TABLE "MODER"."EMBED_OBJECT"(
  "EMBED_OBJECT_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL CHECK("EMBED_OBJECT_ID">=0),
  "TITLE" VARCHAR(256),
  "DESC" VARCHAR(2048),
  "URL" VARCHAR(2000),
  "TIMESTAMP" DATETIME,
--   It's not creation timestamp.
--   
--   It's timestamp in the embed!
  "CREATION" DATETIME NOT NULL,
  "COLOR" INTEGER NOT NULL CHECK("COLOR">=0),
  "FOOTER?" INTEGER CHECK("FOOTER?">=0),
  "IMAGE?" INTEGER CHECK("IMAGE?">=0),
  "THUMBNALE?" INTEGER NOT NULL CHECK("THUMBNALE?">=0),
  "VIDEO?" INTEGER CHECK("VIDEO?">=0),
  "EMBED_AUTHOR?" INTEGER CHECK("EMBED_AUTHOR?">=0),
  "FIELD_COUNT" INTEGER NOT NULL,
  "MESSAGE_ID" INTEGER NOT NULL CHECK("MESSAGE_ID">=0),
  CONSTRAINT "EMBED_OBJECT_ID_UNIQUE"
    UNIQUE("EMBED_OBJECT_ID"),
  CONSTRAINT "fk_EMBED_OBJECT_EMBED_FOOTER_OBJECT1"
    FOREIGN KEY("FOOTER?")
    REFERENCES "EMBED_FOOTER_OBJECT"("EMBED_OBJECT_ID"),
  CONSTRAINT "fk_EMBED_OBJECT_IMAGE_OBJECT1"
    FOREIGN KEY("IMAGE?")
    REFERENCES "IMAGE_OBJECT"("OBJECT_ID"),
  CONSTRAINT "fk_EMBED_OBJECT_IMAGE_OBJECT2"
    FOREIGN KEY("THUMBNALE?")
    REFERENCES "IMAGE_OBJECT"("OBJECT_ID"),
  CONSTRAINT "fk_EMBED_OBJECT_VIDEO_OBJECT1"
    FOREIGN KEY("VIDEO?")
    REFERENCES "VIDEO_OBJECT"("OBJECT_ID"),
  CONSTRAINT "fk_EMBED_OBJECT_EMBED_AUTHOR_OBJECT1"
    FOREIGN KEY("EMBED_AUTHOR?")
    REFERENCES "EMBED_AUTHOR_OBJECT"("EMBED_OBJECT_ID"),
  CONSTRAINT "fk_EMBED_OBJECT_MESSAGE_OBJECT1"
    FOREIGN KEY("MESSAGE_ID")
    REFERENCES "MESSAGE_OBJECT"("MESSAGE_OBJECT_ID")
);
CREATE INDEX "MODER"."EMBED_OBJECT.fk_EMBED_OBJECT_EMBED_FOOTER_OBJECT1_idx" ON "EMBED_OBJECT" ("FOOTER?");
CREATE INDEX "MODER"."EMBED_OBJECT.fk_EMBED_OBJECT_IMAGE_OBJECT1_idx" ON "EMBED_OBJECT" ("IMAGE?");
CREATE INDEX "MODER"."EMBED_OBJECT.fk_EMBED_OBJECT_IMAGE_OBJECT2_idx" ON "EMBED_OBJECT" ("THUMBNALE?");
CREATE INDEX "MODER"."EMBED_OBJECT.fk_EMBED_OBJECT_VIDEO_OBJECT1_idx" ON "EMBED_OBJECT" ("VIDEO?");
CREATE INDEX "MODER"."EMBED_OBJECT.fk_EMBED_OBJECT_EMBED_AUTHOR_OBJECT1_idx" ON "EMBED_OBJECT" ("EMBED_AUTHOR?");
CREATE INDEX "MODER"."EMBED_OBJECT.fk_EMBED_OBJECT_MESSAGE_OBJECT1_idx" ON "EMBED_OBJECT" ("MESSAGE_ID");
CREATE TABLE "MODER"."ATTACHMENT"(
  "OBJECT_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL CHECK("OBJECT_ID">=0),
  "SIZE" INTEGER NOT NULL CHECK("SIZE">=0),
  "MESSAGE_ID" INTEGER NOT NULL CHECK("MESSAGE_ID">=0),
  CONSTRAINT "OBJECT_ID_UNIQUE"
    UNIQUE("OBJECT_ID"),
  CONSTRAINT "fk_ATTACHMENT_MESSAGE_OBJECT1"
    FOREIGN KEY("MESSAGE_ID")
    REFERENCES "MESSAGE_OBJECT"("MESSAGE_OBJECT_ID")
);
CREATE INDEX "MODER"."ATTACHMENT.fk_ATTACHMENT_MESSAGE_OBJECT1_idx" ON "ATTACHMENT" ("MESSAGE_ID");
CREATE TABLE "MODER"."REACTION_OBJECT"(
  "REACTION_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL CHECK("REACTION_ID">=0),
  "REACTOR" INTEGER NOT NULL CHECK("REACTOR">=0),
  "IS_UNICODE" INTEGER NOT NULL CHECK("IS_UNICODE">=0),
  "UNICODE_EMOTE" CHAR(1) NOT NULL,
  "EMOTE_ID" INTEGER NOT NULL CHECK("EMOTE_ID">=0),
  "MESSAGE_OBJECT_ID" INTEGER NOT NULL CHECK("MESSAGE_OBJECT_ID">=0),
  "TIME" DATETIME NOT NULL,
  CONSTRAINT "REACTION_ID_UNIQUE"
    UNIQUE("REACTION_ID"),
  CONSTRAINT "fk_REACTION_OBJECT_MESSAGE_OBJECT1"
    FOREIGN KEY("MESSAGE_OBJECT_ID")
    REFERENCES "MESSAGE_OBJECT"("MESSAGE_OBJECT_ID")
);
CREATE INDEX "MODER"."REACTION_OBJECT.fk_REACTION_OBJECT_MESSAGE_OBJECT1_idx" ON "REACTION_OBJECT" ("MESSAGE_OBJECT_ID");
CREATE TABLE "MODER"."MEMBER_OBJECT_has_GUILD_ROLES"(
  "MEMBER_OBJECT_MEMBER_ID" INTEGER NOT NULL CHECK("MEMBER_OBJECT_MEMBER_ID">=0),
  "GUILD_ROLES_ROLE_ID" INTEGER NOT NULL CHECK("GUILD_ROLES_ROLE_ID">=0),
  PRIMARY KEY("MEMBER_OBJECT_MEMBER_ID","GUILD_ROLES_ROLE_ID"),
  CONSTRAINT "fk_MEMBER_OBJECT_has_GUILD_ROLES_MEMBER_OBJECT1"
    FOREIGN KEY("MEMBER_OBJECT_MEMBER_ID")
    REFERENCES "MEMBER_OBJECT"("MEMBER_ID"),
  CONSTRAINT "fk_MEMBER_OBJECT_has_GUILD_ROLES_GUILD_ROLES1"
    FOREIGN KEY("GUILD_ROLES_ROLE_ID")
    REFERENCES "GUILD_ROLES"("ROLE_ID")
);
CREATE INDEX "MODER"."MEMBER_OBJECT_has_GUILD_ROLES.fk_MEMBER_OBJECT_has_GUILD_ROLES_GUILD_ROLES1_idx" ON "MEMBER_OBJECT_has_GUILD_ROLES" ("GUILD_ROLES_ROLE_ID");
CREATE INDEX "MODER"."MEMBER_OBJECT_has_GUILD_ROLES.fk_MEMBER_OBJECT_has_GUILD_ROLES_MEMBER_OBJECT1_idx" ON "MEMBER_OBJECT_has_GUILD_ROLES" ("MEMBER_OBJECT_MEMBER_ID");
CREATE TABLE "MODER"."GENERIC_MESSAGE_LOG"(
  "EVENT_ID" INTEGER PRIMARY KEY NOT NULL CHECK("EVENT_ID">=0),
  "EVENT_MSG_TYPE" INTEGER NOT NULL CHECK("EVENT_MSG_TYPE">=0),
  "MESSAGE_ID" INTEGER NOT NULL CHECK("MESSAGE_ID">=0),
  "CHANNEL_ID" INTEGER NOT NULL CHECK("CHANNEL_ID">=0),
  "REACTION_OBJECT" INTEGER CHECK("REACTION_OBJECT">=0),
  "MESSAGE_OBJECT_ID" INTEGER NOT NULL CHECK("MESSAGE_OBJECT_ID">=0),
  "EMBED_OBJECT" INTEGER NOT NULL CHECK("EMBED_OBJECT">=0),
  CONSTRAINT "EVENT_ID_UNIQUE"
    UNIQUE("EVENT_ID"),
  CONSTRAINT "MESSAGE_OBJECT_ID_UNIQUE"
    UNIQUE("MESSAGE_OBJECT_ID"),
  CONSTRAINT "REACTION_OBJECT_UNIQUE"
    UNIQUE("REACTION_OBJECT"),
  CONSTRAINT "EMBED_OBJECT_UNIQUE"
    UNIQUE("EMBED_OBJECT"),
  CONSTRAINT "fk_GENERIC_MESSAGE_LOG_EVENT_LOG"
    FOREIGN KEY("EVENT_ID")
    REFERENCES "EVENT_LOG"("EVENT_ID"),
  CONSTRAINT "fk_GENERIC_MESSAGE_LOG_MESSAGE_OBJECT1"
    FOREIGN KEY("MESSAGE_OBJECT_ID")
    REFERENCES "MESSAGE_OBJECT"("MESSAGE_OBJECT_ID"),
  CONSTRAINT "fk_GENERIC_MESSAGE_LOG_REACTION_OBJECT1"
    FOREIGN KEY("REACTION_OBJECT")
    REFERENCES "REACTION_OBJECT"("REACTION_ID"),
  CONSTRAINT "fk_GENERIC_MESSAGE_LOG_EMBED_OBJECT1"
    FOREIGN KEY("EMBED_OBJECT")
    REFERENCES "EMBED_OBJECT"("EMBED_OBJECT_ID")
);
COMMIT;
